//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Fed.rc
//
#define IDD_GOTODIALOG                  101
#define IDS_SETTINGS_CAPTION            102
#define IDD_KEYMAP_PAGE                 103
#define IDS_LANGSHT_CAPTION             105
#define IDD_LANGUAGE_PAGE               106
#define IDB_LIGHTBULB                   107
#define CG_IDS_TIPOFTHEDAY              109
#define CG_IDS_TIPOFTHEDAYMENU          110
#define CG_IDS_DIDYOUKNOW               111
#define CG_IDS_FILE_ABSENT              112
#define CG_IDP_FILE_CORRUPT             113
#define CG_IDS_TIPOFTHEDAYHELP          114
#define IDC_VIEW_LINENUMBER             115
#define IDD_INPUT_DIALOG                116
#define IDD_PREFERENCE_PAGE             117
#define IDD_LANGEDIT_PAGE               118
#define IDD_EXTENSION_PAGE              119
#define IDD_COMMENTS_PAGE               120
#define IDD_KEYWORD_PAGE                121
#define IDD_MACRO_PAGE                  122
#define IDD_COMMENT_PAGE                123
#define IDD_LANGUAGE_DIALOG             124
#define IDD_OPTION_DIALOG               125
#define IDR_MAINFRAME                   128
#define IDR_FEDDOC                      129
#define IDR_FEDPROJ                     130
#define ID_FILE_QUIT                    131
#define ID_FILE_QUITALL                 132
#define ID_FILE_SAVEALL                 133
#define ID_FILE_SAVEPROJECT             134
#define ID_EDIT_FINDAGAIN               135
#define ID_EDIT_PROTECT                 136
#define ID_VIEW_LINENUMBERS             137
#define ID_VIEW_FOLDS                   138
#define ID_VIEW_GOTOLINE                139
#define ID_LANGUAGES_NEW                140
#define IDD_FIND_DIALOG                 144
#define IDD_REPLACE_DIALOG              145
#define IDD_DISPLAY_PAGE                147
#define IDD_EDITOR_PAGE                 148
#define IDB_FINDBAR                     150
#define IDW_FINDCOMBO                   151
#define IDW_REPLACECOMBO                152
#define ID_VIEW_FINDBAR                 153
#define IDR_DUMMYBAR                    154
#define ID_VIEW_DELETEDLINES            161
#define ID_VIEW_OUTPUT                  162
#define ID_LANGUAGE0                    200
#define ID_LANGUAGE99                   299
#define IDC_OPTION_EDITMARKS            300
#define IDC_OPTION_HORIZ                301
#define IDC_OPTION_VERT                 302
#define IDC_OPTION_CHECKFILE            303
#define IDC_OPTION_PROTREADONLY         304
#define IDC_OPTION_BACKSPACE            305
#define IDC_OPTION_LEFTARROW            306
#define IDC_OPTION_SAVEOPTIONS          307
#define IDC_OPTION_SAVEWINDOW           308
#define IDC_OPTION_PASTECURSOR          309
#define IDC_OPTION_SHOWDEBUG            309
#define IDC_OPTION_ENABLEOUTPUTVIEW     310
#define IDC_OPTION_CLEAROUTPUTVIEW      311
#define IDC_OPTION_BACKUPEVERYSAVE      312
#define IDC_OPTION_SHOWWRAPMARK         313
#define IDC_OPTION_BACKUPFIRSTSAVE      314
#define IDC_OPTION_LINEWRAPLENGTH       315
#define IDC_OPTION_LINEWRAPSHADE        316
#define IDC_OPTION_ENABLEUNDO           317
#define IDC_OPTION_SUPPRESSBEEPS        318
#define IDC_OPTION_SHOWLEFTMARGIN       319
#define IDC_OPTION_SINGLEINSTANCE       320
#define IDC_OPTIONS_SAVENOW             321
#define IDC_OPTION_SHOWCLOSEDFOLDCOMMENTS 322
#define ID_TOOL0                        400
#define ID_TOOL99                       499
#define IDC_TOOL_FLAGA                  500
#define IDC_TOOL_FLAGZ                  525
#define IDC_TOOL_LEGENDA                530
#define IDC_TOOL_LEGENDZ                555
#define IDD_TOOL_DIALOG                 560
#define IDD_TOOLLEGEND_DIALOG           561
#define IDC_KEYMAP_APPLY                1004
#define IDC_INPUT_EDIT                  1005
#define IDC_LANGUAGE_LIST1              1008
#define IDC_LANGUAGE_TAB                1009
#define IDC_LANGUAGE_LIST               1010
#define IDC_LANGUAGE_NEW                1011
#define IDC_LANGUAGE_RENAME             1012
#define IDC_LANGUAGE_REMOVE             1013
#define IDC_LANGUAGE_LOAD               1014
#define IDC_LANGUAGE_SAVE               1015
#define IDC_ITEM_REMOVE                 1016
#define IDC_COMMAND_COMBO               1018
#define IDC_EXT_LIST                    1020
#define IDC_EXT_NEW                     1021
#define IDC_EXT_REMOVE                  1022
#define IDC_EXT_REGISTER                1023
#define IDC_EXT_UNREGISTER              1024
#define IDC_EXT_NAME                    1025
#define IDC_INDENT_TAB_SIZE             1027
#define IDC_KEYWORD_LIST                1028
#define IDC_EXT_REGISTER_ALL            1029
#define IDC_KEYWORD_NEW                 1030
#define IDC_EXT_UNREGISTER_ALL          1031
#define IDC_KEYWORD_REMOVE              1032
#define IDC_CASE_SENSITIVE              1033
#define IDC_COMMENT1_START              1041
#define IDC_COMMENT1_END                1042
#define IDC_COMMENT2_START              1043
#define IDC_COMMENT2_END                1044
#define IDC_STRING_ESCAPE               1045
#define IDC_TAB_SIZE                    1046
#define IDC_TEXT_TAB_SIZE               1047
#define IDC_STRING_BOUNDS               1048
#define IDC_CHARACTER_BOUNDS            1049
#define IDC_MACRO_LOAD                  1050
#define IDC_MACRO_SAVE                  1051
#define IDC_MACRO_REMOVE                1052
#define IDC_MACRO_LIST                  1053
#define IDC_MACRO_EDIT                  1054
#define IDC_MACROKEYS_LIST              1055
#define IDC_MACRO_NEW                   1056
#define IDC_MACRO_GETLEARN              1057
#define IDC_KEYMAP_COLOUR1              1060
#define IDC_KEYMAP_COLOUR2              1061
#define IDC_KEYMAP_COLOUR3              1062
#define IDC_KEYMAP_COLOUR4              1063
#define IDC_KEYMAP_COLOUR5              1064
#define IDC_KEYMAP_COLOUR6              1065
#define IDC_REMOVEOPENS                 1071
#define IDC_USE_TAGGED_COLOUR           1072
#define IDC_SEARCH_ALL                  1075
#define IDC_IGNORE_COMMENTS             1076
#define IDC_ADDTOSOURCECONTROL          1084
#define IDC_OPTION_FILENEWERDELTA       1088
#define IDC_KEYSTROKE_EDIT              1200
#define IDC_COMMAND_EDIT                1201
#define IDC_BUTTON_RESTORE              1202
#define IDC_BUTTON_RESTOREALL           1203
#define IDC_KEYS_LIST                   1204
#define IDC_COMMAND_LIST                1205
#define IDC_KEYMAP_LIST                 1206
#define IDC_FIND_COMBO                  1207
#define IDC_REPLACE_COMBO               1208
#define IDC_KEY_FIRST                   0x1000
#define IDC_KEY_BS                      4104
#define IDC_KEY_TAB                     4105
#define IDC_KEY_RETURN                  4109
#define IDC_KEY_PAUSE                   4115
#define IDC_KEY_CAPSLOCK                4116
#define IDC_KEY_ESC                     4123
#define IDC_KEY_SPACE                   4128
#define IDC_KEY_PGUP                    4129
#define IDC_KEY_PGDN                    4130
#define IDC_KEY_END                     4131
#define IDC_KEY_HOME                    4132
#define IDC_KEY_LEFT                    4133
#define IDC_KEY_UP                      4134
#define IDC_KEY_RIGHT                   4135
#define IDC_KEY_DOWN                    4136
#define IDC_KEY_PRINT                   4138
#define IDC_KEY_INSERT                  4141
#define IDC_KEY_DELETE                  4142
#define IDC_KEY_0                       0x1030
#define IDC_KEY_1                       0x1031
#define IDC_KEY_2                       0x1032
#define IDC_KEY_3                       0x1033
#define IDC_KEY_4                       0x1034
#define IDC_KEY_5                       0x1035
#define IDC_KEY_6                       0x1036
#define IDC_KEY_7                       0x1037
#define IDC_KEY_8                       0x1038
#define IDC_KEY_9                       0x1039
#define IDC_KEY_COLON                   4154
#define IDC_KEY_EQUAL                   4155
#define IDC_KEY_COMMA                   4156
#define IDC_KEY_MINUS                   4157
#define IDC_KEY_DOT                     4158
#define IDC_KEY_SLASH                   4159
#define IDC_KEY_QUOTE1                  4160
#define IDC_KEY_A                       0x1041
#define IDC_KEY_B                       0x1042
#define IDC_KEY_C                       0x1043
#define IDC_KEY_D                       0x1044
#define IDC_KEY_E                       0x1045
#define IDC_KEY_F                       0x1046
#define IDC_KEY_G                       0x1047
#define IDC_KEY_H                       0x1048
#define IDC_KEY_I                       0x1049
#define IDC_KEY_J                       0x104A
#define IDC_KEY_K                       0x104B
#define IDC_KEY_L                       0x104C
#define IDC_KEY_M                       0x104D
#define IDC_KEY_N                       0x104E
#define IDC_KEY_O                       0x104F
#define IDC_KEY_P                       0x1050
#define IDC_KEY_Q                       0x1051
#define IDC_KEY_R                       0x1052
#define IDC_KEY_S                       0x1053
#define IDC_KEY_T                       0x1054
#define IDC_KEY_U                       0x1055
#define IDC_KEY_V                       0x1056
#define IDC_KEY_W                       0x1057
#define IDC_KEY_X                       0x1058
#define IDC_KEY_Y                       0x1059
#define IDC_KEY_Z                       0x105A
#define IDC_KEY_OPEN                    4187
#define IDC_KEY_BSLASH                  4188
#define IDC_KEY_CLOSE                   4189
#define IDC_KEY_HASH                    4190
#define IDC_KEY_QUOTEA                  4191
#define IDC_KEY_NUM_0                   4192
#define IDC_KEY_NUM_1                   4193
#define IDC_KEY_NUM_2                   4194
#define IDC_KEY_NUM_3                   4195
#define IDC_KEY_NUM_4                   4196
#define IDC_KEY_NUM_5                   4197
#define IDC_KEY_NUM_6                   4198
#define IDC_KEY_NUM_7                   4199
#define IDC_KEY_NUM_8                   4200
#define IDC_KEY_NUM_9                   4201
#define IDC_KEY_NUMMUL                  4202
#define IDC_KEY_NUMPLUS                 4203
#define IDC_KEY_NUMMINUS                4205
#define IDC_KEY_NUMDEL                  4206
#define IDC_KEY_NUMSLASH                4207
#define IDC_KEY_F1                      4208
#define IDC_KEY_F2                      4209
#define IDC_KEY_F3                      4210
#define IDC_KEY_F4                      4211
#define IDC_KEY_F5                      4212
#define IDC_KEY_F6                      4213
#define IDC_KEY_F7                      4214
#define IDC_KEY_F8                      4215
#define IDC_KEY_F9                      4216
#define IDC_KEY_F10                     4217
#define IDC_KEY_F11                     4218
#define IDC_KEY_F12                     4219
#define IDC_KEY_NUMLOCK                 4240
#define IDC_KEY_LOCK                    4241
#define IDC_KEY_LSHIFT                  4256
#define IDC_KEY_RSHIFT                  4257
#define IDC_KEY_LCTRL                   4258
#define IDC_KEY_RCTRL                   4259
#define IDC_KEY_LALT                    4260
#define IDC_KEY_RALT                    4261
#define IDC_KEY_NUMENTER                4365
#define IDC_KEY_LWIN                    4443
#define IDC_KEY_RWIN                    4444
#define IDC_KEY_MENU                    4445
#define IDC_KEY_LAST                    0x11FF
#define ID_PREFERENCE_SETUP             32771
#define ID_LANGUAGE_SETUP               32772
#define ID_KEYMAP_SETUP                 32774
#define ID_LANGUAGES_LOAD               32775
#define ID_OPTIONS_FONT                 32776
#define ID_FONT_SETUP                   32777
#define ID_COLOUR_SETUP                 32778
#define ID_TOOLS_BUILD                  32779
#define ID_TOOLS_COMPILE                32780
#define ID_TOOLS_CHECKOUT               32781
#define ID_TOOLS_CHECKIN                32782
#define ID_TOOLS_UNDOCHECKOUT           32783
#define ID_TOOLS_ADDTOSOURCECONTROL     32784
#define ID_TOOLS_DIFFERENCE             32785
#define ID_FOLDOPENALL                  32786
#define ID_VIEW_FOLDOPENALL             32787
#define ID_VIEW_OPENALLFOLDSINTHISVIEW  32788
#define ID_VIEW_FOLDCLOSEALL            32789
#define ID_EDIT_FINDUP                  32790
#define ID_EDIT_FINDDOWN                32791
#define ID_TOOLS_TOOL                   32792
#define ID_SPLIT_HORIZ                  32793
#define ID_SPLIT_VERT                   32794
#define ID_INDICATOR_POS                0xE710

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         1089
#define _APS_NEXT_SYMED_VALUE           126
#endif
#endif
